pipeline {
    agent any

    triggers {
        githubPush()
    }
    tools {
        jdk 'JDK21'
        maven 'mvn3'
    }
    environment {
        SCANNER_HOME = tool 'sonar-scanner'
    }
    stages {
        stage('Git checkout') {
            steps {
                git branch : 'main', url: 'https://github.com/NakshatraGowda/foodrush'
            }
        }
        stage('Check Changes') {
            steps {
                script {
                    def changedFiles = sh(
                        script: 'git diff --name-only HEAD~1 HEAD',
                        returnStdout: true
                    ).trim()

                    echo 'Changed files:'
                    echo changedFiles

                    if (!changedFiles.split('\n').any {
                        it.startsWith('api-gateway/')
                    }) {
                        currentBuild.result = 'NOT_BUILT'
                        error('No api-gateway changes. Skipping.')
                    }
                }
            }
        }
        stage('mvn') {
            steps {
                dir('api-gateway') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }
        stage('sonarqube analysis') {
            steps {
                dir('api-gateway') {
                    sh '''
                    $SCANNER_HOME/bin/sonar-scanner \
                    -Dsonar.host.url=http://localhost:9000 \
                    -Dsonar.login=squ_6ee255a90792a5174acdacf77e41142984c21372 \
                    -Dsonar.projectName=foodrush-api-gateway \
                    -Dsonar.projectKey=foodrush-api-gateway \
                    -Dsonar.java.binaries=target/classes \
                '''
                }
            }
        }
        stage('Build docker image') {
            steps {
                dir('api-gateway') {
                    sh 'docker build -t nakshatragowda/api-gateway:${BUILD_NUMBER} .'
                }
            }
        }
        stage('push to dockerhub') {
            steps {
                withDockerRegistry(credentialsId: 'docker-creds', url: 'https://index.docker.io/v1/') {
                    sh 'docker push nakshatragowda/api-gateway:${BUILD_NUMBER}'
                }
            }
        }
    }
}
