pipeline {
    agent any

    tools {
        jdk 'JDK21'
        maven 'mvn3'
        nodejs 'nodejs20'
    }
    environment {
        SCANNER_HOME = tool 'sonar-scanner'
    }
    stages {
        stage('Git checkout') {
            steps {
                git branch : 'main', url: 'https://github.com/NakshatraGowda/foodrush'
            }
        }
        stage('build and test') {
            steps {
                dir('frontend') {
                    sh '''
                        node -v
                        npm -v
                        npm ci
                        npm run build
                    '''
                }
            }
        }
        stage('sonarqube analysis') {
            steps {
                dir('frontend') {
                    sh '''
                        $SCANNER_HOME/bin/sonar-scanner \
                        -Dsonar.host.url=http://localhost:9000 \
                        -Dsonar.login=squ_6ee255a90792a5174acdacf77e41142984c21372 \
                        -Dsonar.projectName=foodrush-frontend \
                        -Dsonar.projectKey=foodrush-frontend \
                        -Dsonar.java.binaries=target/classes \
                    '''
                }
            }
        }
        stage('Build docker image') {
            steps {
                dir('frontend') {
                    sh 'docker build -t nakshatragowda/frontend:${BUILD_NUMBER} .'
                }
            }
        }
        stage('push to dockerhub') {
            steps {
                withDockerRegistry(credentialsId: 'docker-creds', url: 'https://index.docker.io/v1/') {
                    sh 'docker push nakshatragowda/frontend:${BUILD_NUMBER}'
                }
            }
        }
    }
}
