server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://a936bdcbc2e994125a9567993a6e3518-1130392366.ap-south-1.elb.amazonaws.com/"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: menu-service
          uri: http://menu-service-service
          predicates:
            - Path=/api/menu/**
          filters:
            - StripPrefix=0

        - id: order-service
          uri: http://order-service-service
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=0

        - id: payment-service
          uri: http://payment-service-service
          predicates:
            - Path=/api/payments/**
          filters:
            - StripPrefix=0

management:
  endpoints:
    web:
      exposure:
        include: health,info