pipeline {
    agent any

    tools {
        jdk 'JDK21'
        maven 'mvn3'
    }
    environment {
        SCANNER_HOME = tool 'sonar-scanner'
    }
    stages {
        stage('Git checkout') {
            steps {
                git branch : 'main', url: 'https://github.com/NakshatraGowda/foodrush'
            }
        }
        stage('Debug') {
            steps {
                sh '''
                    echo "JAVA_HOME=$JAVA_HOME"
                    which java
                    java -version
                    mvn -version
                '''
            }
        }
        stage('mvn') {
            steps {
                dir('payment-service') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }
        stage('sonarqube analysis') {
            steps {
                dir('payment-service') {
                    sh '''
                    $SCANNER_HOME/bin/sonar-scanner \
                    -Dsonar.host.url=http://localhost:9000 \
                    -Dsonar.login=squ_6ee255a90792a5174acdacf77e41142984c21372 \
                    -Dsonar.projectName=foodrush-payment-service \
                    -Dsonar.projectKey=foodrush-payment-service \
                    -Dsonar.java.binaries=target/classes \
                '''
                }
            }
        }
        stage('Build docker image') {
            steps {
                dir('payment-service') {
                    sh 'docker build -t nakshatragowda/payment-service:${BUILD_NUMBER} .'
                }
            }
        }
        stage('push to dockerhub') {
            steps {
                withDockerRegistry(credentialsId: 'docker-creds', url: 'https://index.docker.io/v1/') {
                    sh 'docker push nakshatragowda/payment-service:${BUILD_NUMBER}'
                }
            }
        }
    }
}
